apiVersion: v1
kind: Service
metadata:
  name: git-manage-service
  namespace: default
spec:
  selector:
    app: git-manage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
